config/routes.rb
ScratchCms::Application.routes.draw do

  resources :blogs
  resources :blogentries
  resources :custompages
  resources :users
  resources :sessions, only: [:new, :create, :delete]

  resources :projects

  root to: 'pages#home'

  match '/about' => 'pages#about', :mode => 'main',    via: 'get'
  match '/error' => 'pages#error',    via: 'get'

  match '/signup',  to: 'users#new',    via: 'get'

  match '/login' => 'sessions#new',    via: 'get'
  match '/logout' => 'sessions#destroy', via: :delete
  match '/dashboard' => 'users#show',    via: 'get'

  match '/blogs/:id/manage' => 'blogs#manage', via: 'get', as: 'blogs_manage'

end

app/models/blog.rb
# == Schema Information
#
# Table name: blogs
#
#  id         :integer          not null, primary key
#  content    :string(255)
#  title      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Blog < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :user
  has_many :blogentries, dependent: :destroy

  validates :content, presence: true, length: {maximum: 500}
  validates :title, presence: true
  validates :user_id, presence: true

  default_scope -> { order(created_at: :desc) }
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :signed_in_user, :except => [:show]
  
  def new
    @blog = Blog.new
  end

  def edit
    @blog = Blog.friendly.find(params[:id])
    @blogentries = @blog.blogentries
  end

  def manage
    @blog = Blog.friendly.find(params[:id])
    @blogentries = @blog.blogentries.paginate(page: params[:page], :per_page => 10) # each blogentry sorted by created_at
  end

  def show
    privileged = (params[:privileged].downcase rescue 'false') == 'yes'
    @blog = Blog.friendly.find(params[:id])
    # don't paginate the results, show all on one page
    @blogentries = @blog.blogentries
    if (@blog.draft == true && !privileged)
      redirect_to root_path
    end
  end

  def index
    @blogs = current_user.blogs
  end

  def update
    @blog = Blog.friendly.find(params[:id])
    if @blog.update_attributes(blog_params)
      flash[:success] = "Blog updated!"
      redirect_to dashboard_path(:link => "blogs")
    else
      render 'edit'
    end
  end

  def destroy
    Blog.friendly.find(params[:id]).destroy
    flash[:success] = "Blog deleted."
    redirect_to dashboard_path(:link => "blogs")
  end

  def create
    @blog = current_user.blogs.build(blog_params)
    if @blog.save
      flash[:success] = "Blog created successfully!"
      redirect_to dashboard_path(:link => "blogs")
    else
      render 'new'
    end
  end

  private

    def blog_params # strong params
      params.require(:blog).permit(:content, :title, :draft)
    end

    def signed_in_user
      redirect_to login_url, notice: "Please sign in." unless signed_in?
    end
    
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blogs/edit.html.erb
<% provide(:mode, "management") %>
<% provide(:title, "Edit Blog") %>

<div class="container-fluid">
  <div class="row-fluid">
    <%= render 'layouts/sidebar' %>
    <script type="text/javascript">
      $('#blogs-link').removeClass("inactive").addClass("active") // change the "inactive" class to "active"
    </script>
  
    <div class="span8 dashboard">
      <h1>Edit Title and Description</h1>
        
        <%= form_for(@blog) do |f| %>
          <%= render 'shared/error_messages', object: f.object %>

            <%= f.label :title %>
            <%= f.text_field :title %>

          <div class="redactor_box" data-no-turbolink>
            <%= f.text_area :content, placeholder: "Blog description goes here...", :id => "redactor"%>
          </div>

          <br>

          <div class="draft-checkbox-container">
              <%= f.check_box :draft, :class => "pull-left" %> <%=f.label "Draft", :class => "pull-right" %>
          </div>

          <br>
          <br>

          <%= f.submit "Save", class: "btn btn-large btn-success" %>
        <% end %>

    </div>
  </div>
</div>
<%# add some space so that footer bar doesn't cover anything %>
<br>
<br>

app/views/blogs/index.html.erb
<%= link_to 'New Blog', new_blog_path, 'data-no-turbolink' => true, :class => "btn btn-large btn-primary" %>
<br>
<br>
<% @blogs.each do |blog| %>
  <div class="row-fluid">
      <div class="page-list">
        <h2>
          <% if blog.draft == true %>
            <%= blog.title %> <%= '- <i>draft</i>'.html_safe %>
          <% else %>
            <%= blog.title %>
          <% end %>
          <%= link_to 'Delete', blog, method: :delete, :class => "btn btn-danger pull-right",
                                     data: { confirm: 'Are you sure?' }%>
        </h2>
        <p>
          <%= truncate_html blog.content.html_safe, length: 80 %>
        </p>
        <p>
          <% #according to Rails API, link_to(body, url, html_options) %>
          <%= link_to 'New Entry', new_blogentry_path(:blogid => blog.friendly_id), 'data-no-turbolink' => true, :class => 'btn' %> <%# see friendly_id documentation %>
          <%= link_to 'Manage', { :controller => "blogs", :action => "manage", :id => blog.friendly_id }, { :class => "btn" } %> <%# see friendly_id documentation %>
        </p>
      </div>
      <!--/span-->
    </div>
<% end %>
<%= will_paginate @blogs %>
<%# add some space so that footer bar doesn't cover anything %>
<br>
<br>

app/views/blogs/manage.html.erb
<% provide(:mode, 'management') %>
<% provide(:title, 'Manage Blog') %>

<div class="container-fluid">
  <div class="row-fluid">
    <%= render 'layouts/sidebar' %>
    <script type="text/javascript">
      $('#blogs-link').removeClass("inactive").addClass("active") // change the "inactive" class to "active"
    </script>
  
    <div class="span8 dashboard">
      <div class="page-list">
        <h2>Edit Title and Description<%= link_to 'Edit', edit_blog_path(@blog), 'data-no-turbolink' => true, :class => "btn pull-right"  %></h2>
      </div>
      <div class="page-list">
        <h2>Blog Entries
        <% # this passes :blogid to blogentries_controller/new, where it can be accessed with "params[:blogid]" %>
        <%= link_to 'New Entry', new_blogentry_path(:blogid => @blog), 'data-no-turbolink' => true, :class => 'btn btn-primary pull-right' %>
        </h2>
        <br>
        <% @blogentries.order('created_at DESC').each do |blogentry| %>
          <div class="row-fluid">
              <div class="sub-page-list pull-right blogentry-preview">
                <h3>
                  <% if blogentry.draft == true %>
                    <%= "#{blogentry.title} - <i style=\"color:#BDBDBD;\">draft, #{blogentry.created_at.strftime("%F")}</i>".html_safe %>
                  <% else %>
                    <%= "#{blogentry.title} - <i style=\"color:#BDBDBD;\">#{blogentry.created_at.strftime("%F")}</i>".html_safe %>
                  <% end %>
                  <%= link_to 'Destroy', blogentry, method: :delete, :class => "btn btn-danger pull-right",
                                             data: { confirm: 'Are you sure?' }%>
                </h3>
                <p>
                  <%= truncate_html blogentry.content.html_safe, length: 80 %>
                </p>
                <p>
                  <% #according to Rails API, link_to(body, url, html_options) %>
                  <%  from_page = params[:page].nil? ? "1" : params[:page] %>
                  <%= link_to 'Edit', edit_blogentry_path(blogentry, :from => from_page), 'data-no-turbolink' => true, :class => "btn" %>
                  
                </p>
              </div>
              <!--/span-->
            </div>
        <% end %>
      </div>
      <%= will_paginate @blogentries %>
    </div>
  </div>
</div>
<%# add some space so that footer bar doesn't cover anything %>
<br>
<br>

app/views/blogs/new.html.erb
<% provide(:mode, 'management') %>
<% provide(:title, 'Create Blog') %>

<div class="container-fluid">
  <div class="row-fluid">
    <%= render 'layouts/sidebar' %>
    <script type="text/javascript">
      $('#blogs-link').removeClass("inactive").addClass("active") // change the "inactive" class to "active"
    </script>

    <div class="span8 dashboard">
      <h1>Create a New Blog</h1>

        <%= form_for(@blog) do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
          
          <%= f.label :title %>
          <%= f.text_field :title %>

          <div class="redactor_box">
            <%= f.text_area :content, placeholder: "Write a description for this blog...", :id => "redactor"%>
          </div>

          <br>

          <div class="draft-checkbox-container">
              <%= f.check_box :draft, :class => "pull-left" %> <%=f.label "Draft", :class => "pull-right" %>
          </div>

          <br>
          <br>

          <%= f.submit "Create Blog", class: "btn btn-large btn-success" %>
        <% end %>

    </div>
  </div>
</div>
<%# add some space so that footer bar doesn't cover anything %>
<br>
<br>

app/views/blogs/show.html.erb
<% provide :title, @blog.title %>

<div class="container-content">
	<h1><%= @blog.title %></h1>
	<%= @blog.content.html_safe %>
	<br>
  <br>
	<% @blogentries.each do |blogentry| %>
    <% if blogentry.draft == false %>
      <div class="row-fluid">
          <div class="page-list">
            <h3>
              <%= blogentry.title %>
            </h3>

            <p>
              <i>Posted at <%= blogentry.created_at.strftime('%Y %B %d %I:%M %P')%></i>
            </p>
            <p>
              <%= blogentry.content.html_safe %>
            </p>
          </div>
          <!--/span-->
        </div>
    <% end %>
  <% end %>
	<br>
</div>