config/routes.rb
ScratchCms::Application.routes.draw do

  resources :blogs
  resources :blogentries
  resources :custompages
  resources :users
  resources :sessions, only: [:new, :create, :delete]

  resources :projects

  root to: 'pages#home'

  match '/about' => 'pages#about', :mode => 'main',    via: 'get'
  match '/error' => 'pages#error',    via: 'get'

  match '/signup',  to: 'users#new',    via: 'get'

  match '/login' => 'sessions#new',    via: 'get'
  match '/logout' => 'sessions#destroy', via: :delete
  match '/dashboard' => 'users#show',    via: 'get'

  match '/blogs/:id/manage' => 'blogs#manage', via: 'get', as: 'blogs_manage'

end

app/views/layouts/_dashboard_header.html.erb
<!-- Redactor editor -->
<script type="text/javascript">
$(document).ready(
	function()
	{
		$('#redactor').redactor({
			fixed: true,
			minHeight: 300,
			linebreaks: true // use <br> when user presses enter instead of <p>
		});
	}
);
</script>
<div class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner-dashboard">
		<div class="container-fluid">
			<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to image_tag(asset_path('jack.gif')), root_path, 'data-no-turbolink' => true, :class => "brand" %>
			<div class="nav-collapse collapse">
				<p class="navbar-text pull-right">
					
				</p>
				<ul class="nav pull-right">
					<% if signed_in? %>
						<li class="dropdown">
							<%= link_to '#', :class => "dropdown-toggle", "data-toggle" => "dropdown" do %>
	           	  				Logged in as <%= current_user.name %> <b class="caret"></b>
           	  				<% end %>
           	  				<ul class="dropdown-menu">
           	  					<li>
           	  						<%# deprecated way of rendering users/edit, keeping code for reference %>
           	  						<%#= link_to 'Account Settings', dashboard_path(:link => 'settings'), remote: true %>
           	  						<%= link_to 'Account Settings', edit_user_path(:id => current_user.friendly_id) %>
           	  					</li>
           	  					<li>
           	  						<%= link_to "Sign Out", logout_path, method: :delete %>
           	  					</li>
           	  				</ul>
						</li>
					<% end %>
				</ul>
			</div>
			<!--/.nav-collapse -->
		</div>
	</div>
</div>

app/views/layouts/_footer.html.erb
<% if yield(:mode) == 'management' %>

    <footer id="footer-container" class="footer navbar navbar-fixed-bottom">

        <table>
            <tr>
                <td class="cell-left" rowspan="2">
                    &nbsp;&nbsp; <%= link_to image_tag('ScratchCMS.png', alt: 'Scratch CMS', height: 25, width: 112), 'http://scratch-cms.herokuapp.com' %>
                </td>

            </tr>
            <tr>
                <td class="cell-right">
                    <span class="copyright-text">
                        Copyright &#169; 2013 Scratch CMS · All Rights Reserved.
                    </span>
                </td>
            </tr>
        </table>

    </footer>

<% else %>
    <footer id="footer" class="footer">
        <div class="container">
            <div class="row credits">
                <div class="row copyright">
                    <div class="span12">
                        Copyright &#169; 2013 Scratch CMS. All rights reserved.
                    </div>
                </div> 
                <div class="span12">
                    <div class="row social">
                        <p>This website is built from</p>
                        <p><%= link_to image_tag(asset_path("builtfromScratchCMS.png")), 'http://scratch-cms.herokuapp.com/' %></p>
                    </div>
                </div>  
            </div>
        </div>

    </footer>
<% end %>

app/views/layouts/_header.html.erb
<% if yield(:title) == 'Home' %> <%# fancy navbar on home page %>
  <div class="navbar transparent navbar-inverse navbar-fixed-top">
<% else %>
  <div class="navbar navbar-inverse navbar-fixed-top">
<% end %>
    <div class="navbar-inner">
    	<div class="container"> 
  			<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
  				<span class="icon-bar"></span>
  				<span class="icon-bar"></span>
  				<span class="icon-bar"></span>
  			</button>
        <%= link_to image_tag(asset_path('jack.gif')), root_path, 'data-no-turbolink' => true, :class => "brand" %>
  			<div class="nav-collapse collapse">
  				<ul class="nav pull-right">
                <% if User.first %>
                  <li>
                    <%= link_to "About", User.first.custompages.find_by_title("About") %>
                  </li>
                  <li class="dropdown">
                    <%= link_to 'Projects <b class="caret"></b>'.html_safe, '#', :class => "dropdown-toggle", "data-toggle" => "dropdown"  %>
                    <ul class="dropdown-menu">
                      <% User.first.projects.each do |project| %>
                        <% if project.draft == false %>
                          <li>
                            <%= link_to project.title, project %>
                          </li>
                        <% end %>
                      <% end %>
                    </ul>
                    <%# add blogs %>
                  </li>
                  <li class="dropdown">
                    <%= link_to 'Blogs <b class="caret"></b>'.html_safe, '#', :class => "dropdown-toggle", "data-toggle" => "dropdown" %>
                    <ul class="dropdown-menu" >
                      <% User.first.blogs.each do |blog| %>
                        <% if blog.draft == false %>
                          <li>
                            <%= link_to blog.title, blog %>
                          </li>
                        <% end %>
                      <% end %>
                    </ul>
                  </li>
                <% end %>
  				</ul>
  			</div>
  		</div>
  	</div>
  </div>

app/views/layouts/_sidebar.html.erb
		<div class="span3">
			<div id="my-links" class="well sidebar-nav">
				<ul class="nav nav-list">
					<li class="nav-header">
						Control Panel
					</li>
					<li id="projects-link" class="inactive">
						<%= link_to 'Projects', dashboard_path(:link => 'projects') %>
					</li>
					<li id="blogs-link" class="inactive">
						<%= link_to 'Blogs', dashboard_path(:link => 'blogs') %>
					</li>
					<li id="custompages-link" class="inactive">
						<%= link_to 'Custom Category', dashboard_path(:link => 'custompages') %>
					</li>
					<li id="about-scratch-link" class="inactive">
						<%= link_to 'About Scratch CMS', dashboard_path(:link => 'about') %>
					</li>
				</ul>
			</div>
		</div>

app/views/layouts/_sidebar_main.html.erb
		<div class="span3">
			<div id="my-links" class="well sidebar-nav">
				<ul class="nav nav-list">
					<li class="nav-header">
						Control Panel
					</li>
					<li id="projects-link" class="inactive">
						<%= link_to 'Projects', dashboard_path(:link => 'projects'), remote: true %>
					</li>
					<li id="blogs-link" class="inactive">
						<%= link_to 'Blogs', dashboard_path(:link => 'blogs'), remote: true %>
					</li>
					<li id="custompages-link" class="inactive">
						<%= link_to 'Custom Category', dashboard_path(:link => 'custompages'), remote: true %>
					</li>
					<li id="about-scratch-link" class="inactive">
						<%= link_to 'About Scratch CMS', dashboard_path(:link => 'about'), remote: true %>
					</li>
				</ul>
			</div>
		</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
	<title><%= full_title(yield(:title)) %></title>
	<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
	<%= favicon_link_tag 'SnobbyFrenchSmiley-favicon.png' %>
	<script type="text/javascript">
		var _gaq = _gaq || [];
		_gaq.push(['_setAccount', 'UA-33324771-1']);
		_gaq.push(['_trackPageview']);

		(function() {
			var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		})();
	</script>
</head>
<body>
	<div class="public-wrapper">
		<% if yield(:mode) == 'management' %>
			<%= render 'layouts/dashboard_header' %>
			<div class="navbar-placeholder">
			</div>
		<% else %>
			<%= render 'layouts/header' %>
		<% end %>

		<% if yield(:mode) == 'management' %>
			<div class="container-fluid">
		<% else %>
			<div class="container">
		<% end %>
			  <% flash.each do |key, value| %>
			    <div id="flash" class="alert alert-<%= key %>"><%= value %></div>
			  <% end %>
			</div>

			<%= yield %>
			<%= render 'layouts/footer' %>
			<%#= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>


			<%# if yield(:mode) == 'management' %>
				<!-- <div class="management-wrapper"> -->
			<%# end %>
			<%#= yield %>
			<%# if yield(:mode) == 'management' %>
				<!-- </div> -->
			<%# end %>
			<%#= render 'layouts/footer' %>
			<%#= debug(params) if Rails.env.development? %>